#!/bin/tcsh -f
echo "***                    *** ***        ***********      **********  *********     ***********"
echo " ***                  ***  ***       ***************   **********  *********     ***********"
echo "   ***               ***   ***        ****                ***      ***    ***    ****     ***"
echo "    ***             ***    ***        ******              ***      ***     ***   ****      ***"
echo "      ***          ***     ***         **************     ***      ***    ***    ****      ***"
echo "       ***        ***      ***                 ******     ***      ***  ***      ****      ***"
echo "        ***     ***       ***                  *****     ***      ***           ****     ***"
echo "          ***   ***        *********    *************   *********  ***           ****   ***"
echo "            ******         *********      *********     *********  ***           *******"
echo "     An user interface (UI) that takes an RTL netlist and SDC constraints as the input and generates"
echo " the synthesized netlist and pre-layout timing report as the outputs. For synthesis, the Yosys tool is used while"
echo "                          for generating the timing report, Opentimer is used"
echo " "
echo "                               Developed and maintained by Kevin Pinto"
echo "    For queries and requests pertaining to the scripts please drop an email to kevinpinto98@gmail.com"
echo




set my_work_dir =  `pwd`

#--------------------------------------------#
#----------Tool Initialization---------------#
#--------------------------------------------#


if ($#argv != 1) then
	echo "Info: Please provide the csv file"
	exit 1		
endif

if (! -f $argv[1] || $argv[1] == "-help") then
	if ($argv[1] != "-help") then
		echo "Error: Cannot find csv file $argv[1]. Exiting ..."
		exit 1
	else
		echo USAGE: ./vsdsynth \<csv file\>
		echo
		echo where \<csv file\> consists of 2 columns, below keyword being in 1st column and is Case Sensitive. Please request Kevin Pinto for sample csv file
		echo
		echo \<Design Name\> is the name of top level module
		echo
		echo \<Output Directory\> is the name of output directory where you want to dump synthesis script, sunthesized netlist and timing reports
		echo
		echo \<Netlist Directory\> is the name of directory where all RTL netlist are present
		echo
		echo \<Early Library Path\> is the file path of the early cell library to be used for STA
		echo
		echo \<Late Library Path\> is the file path of the late cell library to be used for STA
		echo
		echo \<COnstraints file\> is the csv file path of constraints to be used for STA
		exit 1
	endif
else
	tclsh vlsipd.tcl $argv[1]
endif
